---
abstract: 'emit POE events for Irssi signals'
author:
  - 'Martijn van Beers  <martijn@eekeek.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Session-Irssi
no_index:
  directory:
    - inc
    - t
provides:
  POE::Session::Irssi:
    file: lib/POE/Session/Irssi.pm
    version: 0.50
requires:
  Carp: 1.08
  Irssi: 0
  POE: 1.003
  POE::Loop::Glib: 0.0036
  perl: 5.6.0
version: 0.50
