# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Session-Irssi
version:      0.2
version_from: lib/POE/Session/Irssi.pm
installdirs:  site
requires:
    POE:                           0.31
    POE::Loop::Glib:               0.0023

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
