---
name: POE-Session-Irssi
version: 0.4
author:
  - 'Martijn van Beers  <martijn@eekeek.org>'
abstract: emit POE events for Irssi signals
license: gpl
requires:
  POE: 0.31
  POE::Loop::Glib: 0.0023
  Sub::Uplevel: 0.14
provides:
  POE::Session::Irssi:
    file: lib/POE/Session/Irssi.pm
    version: 0.4
generated_by: Module::Build version 0.26
